services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123@Rohith"
      MYSQL_DATABASE: "Files"
      # MYSQL_USER: "root"
      # MYSQL_PASSWORD: "123@Rohith"
    ports:
      - "3307:3306"  # Expose MySQL on the default port
    volumes:
      - db_data:/var/lib/mysql  # Persist database data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:123@Rohith@localhost/Files
    depends_on:
      - db
    ports:
      - "8080:8080"  # Expose the app's port if needed

volumes:
  db_data:
